name: leavo
description: tracks public transport in real-time and notifies you exactly when it's time to leave.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  http: ^0.13.6
  csv: ^5.1.1
  autocomplete_textfield: ^2.0.1
  audioplayers: ^5.2.1
  dio: ^5.4.0
  intl: ^0.19.0
  flutter_app_badger: ^1.5.0
  flutter_local_notifications: ^16.2.0
  flutter_background: ^1.2.0
  app_to_foreground: ^0.0.3
  flutter_foreground_task: ^6.1.2
  string_similarity: ^2.0.0
  dart_levenshtein: ^1.0.1
  provider: ^6.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - /Users/idansegal/Documents/Coding/Leavo/assets/icons/
    - /Users/idansegal/Documents/Coding/Leavo/assets/sounds/Alert.mp3
    - /Users/idansegal/Documents/Coding/Leavo/assets/databases/Stops.csv
    - /Users/idansegal/Documents/Coding/Leavo/assets/databases/Lines.csv
    - /Users/idansegal/Documents/Coding/Leavo/assets/databases/lineToStops.csv
